### ISSUE TITLE
ValueError at matrixgroup.py", line 82

### ISSUE THREAD

**Issue by 3togo** [DCC-Lab/RayTracing#308]
Why the following code won't work?

`from raytracing import *

path = ImagingPath()
path.label = "Test"
path.objectHeight = 20
path.append(Space(d=5))
path.append(DielectricInterface(R=-20, n1=1.55, n2=1., diameter=25, label='Front'))
#path.append(Space(d=50))
path.display()`

Below is the error message:
Traceback (most recent call last):
  File "test_ray_tracing.py", line 7, in <module>
    path.append(DielectricInterface(R=-20, n1=1.55, n2=1., diameter=25, label='Front'))
  File "/usr/local/lib/python3.8/dist-packages/raytracing/matrixgroup.py", line 82, in append
    raise ValueError(msg)
ValueError: Mismatch of indices between last element and appended element

**Comment by 3togo** [comment]
Problem fixed.

I need to specify the n value of the space as well.

```

from raytracing import *

path = ImagingPath()
path.label = "Test"
path.objectHeight = 20
path.append(Space(d=5, n=1.55))
path.append(DielectricInterface(R=-20, n1=1.55, n2=1., diameter=25, label='Front'))
#path.append(Space(d=50))
path.display()

```
